---
title: "Metrics and ML - Data Cleaning"
author: "Sydney Gu and Isabella Lin"
date: "2025-02-02"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r}
library(dplyr)
library(tidyr)
library(haven)
library(glmnet)
library(knitr)
library(kableExtra)
library(caret)
library(stats)
```

```{r}
cex <- read_dta("~/Desktop/metrics_and_ml/ecma31330_final/113270/cexall.dta")
psid <- read_dta("~/Desktop/metrics_and_ml/ecma31330_final/113270/data.dta")
```

Adjust hours worked values in CEX dataframe:
```{r}
cex <- cex %>%
  mutate(hours = weekh * hourh)
cex <- cex %>%
  mutate(hourw = weekw * hourw)
```

Standardize household income variables:
```{r}
# for PSID 
psid <- psid %>%
  mutate(total_income = tyhw + tyoth)
```

```{r}
psid <- psid %>%
  mutate(hw_laborinc = ly + wly)
```

```{r}
cex <- cex %>%
  mutate(hw_wages = wageh + wagew)
```

```{r}
psid <- psid %>%
  mutate(hwage_inc = wages * hours)
```

As the CEX data on income is adjusted to the annual CPI of when the survey data was collected, we will also adjust the income data from the PSID dataset with the annual CPI:
```{r}
# Set the seed for reproducibility
set.seed(123)

# Step 1: Convert all columns to numeric (excluding 'food' column for prediction)
cex <- cex %>%
  mutate(across(everything(), ~ as.numeric(as.character(.)), .names = "{.col}_2"))
cex <- cex %>%
  select(ends_with("_2"))
head(cex)
```

```{r}
cex$adj_income <- cex$income_2*cex$cpi_2/172.2
```

Now, let's rename the variables that have the same values across both datasets:
```{r}
cex <- cex %>%
  rename(fsize = ncomp)
```
```{r}
cex <- cex %>%
  rename(kids = kid)
```


