---
title: "Metrics and ML - Final Paper"
author: "Sydney Gu and Isabella Lin"
date: "2025-02-02"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(tidyr)
library(haven)
```

```{r}
cex_final <- read_dta("~/Desktop/metrics_and_ml/Replication_materials/CES/data/cex_final_8022.dta")
```
```{r}
cex_final <- cex_final[, colMeans(is.na(cex_final)) < 0.9]  # Keep columns with <50% missing
cex_final <- cex_final[rowMeans(is.na(cex_final)) < 0.9, ]  # Keep rows with <50% missing


cex_final <- cex_final %>%
  mutate(across(where(is.numeric), ~replace_na(., median(., na.rm = TRUE)))) %>%
  mutate(across(where(is.character), ~replace_na(., "Unknown")))
head(cex_final)

str(cex_final)
colSums(is.na(cex_final))

```



```{r}
cpi <- read_dta("~/Desktop/metrics_and_ml/Replication/cpi.dta")
head(cpi)

cex <- read_dta("~/Desktop/metrics_and_ml/Replication/CEX_sampleA_80_22.dta")
print(dim(cex))
april2k <- read.csv("~/Desktop/metrics_and_ml/Replication/CPIAUCSL_april2000.csv")
head(april2k)
```
CPI dataset contains the quarterly U.S. CPI values from 1947-2023. 
Consumer Price Index for All Urban Consumers: All Items in
U.S. City Average (CPIAUCSL)

```{r}
cex <- cex[, colMeans(is.na(cex)) < 0.9]  # Keep columns with <50% missing
cex <- cex[rowMeans(is.na(cex)) < 0.9, ]  # Keep rows with <50% missing


cex <- cex %>%
  mutate(across(where(is.numeric), ~replace_na(., median(., na.rm = TRUE)))) %>%
  mutate(across(where(is.character), ~replace_na(., "Unknown")))
head(cex)

str(cex)
colSums(is.na(cex))

```
```{r}
# Count unique values
summary_counts <- cex %>%
  count(year, name = "Frequency")

print(summary_counts)
```

Remove all columns where over half of the entries are empty or blank:
```{r}
remove_empty_columns <- function(df) {
  df[, colSums(df == "" | is.na(df)) <= (nrow(df) / 2)]
}
```
```{r}
cleaned_cex <- remove_empty_columns(cex)
```

