---
title: "Metrics and ML - Original Imputation Method"
author: "Sydney Gu and Isabella Lin"
date: "2025-02-02"
output:
  pdf_document: default
  html_document:
    df_print: paged
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, warning=FALSE}
library(dplyr)
library(tidyr)
library(haven)
library(glmnet)
library(data.table)
library(AER)
```

```{r}
cexall <- read_dta("~/Desktop/metrics_and_ml/ecma31330_final/113270/cexall.dta")
```

```{r}
# Generate education levels
cexall <- cexall %>%
  mutate(
    educ = case_when(
      educh %in% c(7, 1, 2) ~ 1,
      educh == 3 ~ 2,
      educh %in% c(4, 5, 6) ~ 3
    ),
    white = ifelse(race == "1", 1, 0)  # Dummy for white husband
  )
```


```{r}
# Generate education dummies
cexall <- cexall %>%
  mutate(
    edd1 = ifelse(educ == 1, 1, 0),
    edd2 = ifelse(educ == 2, 1, 0),
    edd3 = ifelse(educ == 3, 1, 0)
  )
```

```{r}
# Generate regional dummies
cexall <- cexall %>%
  mutate(across(starts_with("region"), ~ as.numeric(. == region), .names = "regd{col}"))
```

```{r}
# Generate birth cohort variable
cexall <- cexall %>%
  mutate(
    coh = case_when(
      yb >= 1955 & yb <= 1959 ~ 1,
      yb >= 1950 & yb <= 1954 ~ 2,
      yb >= 1945 & yb <= 1949 ~ 3,
      yb >= 1940 & yb <= 1944 ~ 4,
      yb >= 1935 & yb <= 1939 ~ 5,
      yb >= 1930 & yb <= 1934 ~ 6,
      yb >= 1925 & yb <= 1929 ~ 7,
      yb >= 1920 & yb <= 1924 ~ 8
    )
  ) %>%
  filter(!is.na(coh))
```

```{r}
# Generate cohort dummies
for (i in 1:8) {
  cexall <- cexall %>%
    mutate(!!paste0("cohd", i) := as.numeric(coh == i))
}
```

```{r}
# Adjust price and log transformations
cexall <- cexall %>%
  mutate(
    pf = pf / 100,
    lq = log((food + fout) / pf),
    lp = log(pf),
    lx = log(ndur),
    lxs = log(ndurplus),
    lX = log(cons2),
    lXs = log(cons2 + (ndurplus - ndur))
  )
```

```{r}
# Work hours calculations
cexall <- cexall %>%
  mutate(
    weekh = replace_na(weekh, 0),
    hourh = replace_na(hourh, 0),
    yhourh = weekh * hourh,
    parth = as.numeric(yhourh > 0),
    weekw = replace_na(weekw, 0),
    hourw = replace_na(hourw, 0),
    yhourw = weekw * hourw,
    partw = as.numeric(yhourw > 0)
  )
```

```{r}
# Interaction terms with education
cexall <- cexall %>%
  mutate(
    lxed2 = lx * edd2,
    lxed3 = lx * edd3,
    lxsed2 = lxs * edd2,
    lxsed3 = lxs * edd3,
    lXed2 = lX * edd2,
    lXed3 = lX * edd3,
    lXsed2 = lXs * edd2,
    lXsed3 = lXs * edd3
  )
```

```{r}
# Generate kid categories
cexall <- cexall %>%
  mutate(
    kidcat = case_when(
      kid == 0 ~ 0,
      kid == 1 ~ 1,
      kid == 2 ~ 2,
      kid >= 4 ~ 4
    )
  )
```

Generate kid dummies:
```{r}
cexall <- cexall %>%
  mutate(
    kidcat = case_when(
      kid == 0 ~ 0,
      kid == 1 ~ 1,
      kid == 2 ~ 2,
      kid >= 4 ~ 4  # Ensures categories are only 0, 1, 2, 4
    )
  )
```
```{r}
cexall <- cexall %>%
  mutate(
    kidd0 = as.numeric(kidcat == 0),
    kidd1 = as.numeric(kidcat == 1),
    kidd2 = as.numeric(kidcat == 2),
    kidd4 = as.numeric(kidcat == 4)
  )
```

```{r}
# Create kid interaction terms
cexall <- cexall %>%
  mutate(
    lxkid0 = lx * kidd0,
    lxkid1 = lx * kidd1,
    lxkid2 = lx * kidd2,
    lxkid4 = lx * kidd4
  )
```


```{r}
# Year dummies
for (i in unique(cexall$year)) {
  cexall <- cexall %>%
    mutate(!!paste0("yrd", i) := as.numeric(year == i))
}
```

```{r}
finprice <- read_dta("~/Desktop/metrics_and_ml/ecma31330_final/113270/finprice.dta")
```

```{r}
# Merge with external price data
cexall <- merge(cexall, finprice, by = "year")
  # filter(!is.na(palc))

cexall <- cexall %>% filter(!is.na(palc))
```

```{r}
# Log transformations for additional prices
cexall <- cexall %>%
  mutate(
    lpalc = log(palc / 100),
    lpfut = log(pfutil / 100),
    lptra = log(ptran / 100),
    lwh = log(wageh / (hourh * weekh)),
    lww = log(wagew / (hourw * weekw)),
    age2 = age^2
  )
```

```{r}
# Grouped means for cohort, education, and year
cexall <- cexall %>%
  group_by(coh, educ, year) %>%
  mutate(lwhi = mean(lwh, na.rm = TRUE), lwwi = mean(lww, na.rm = TRUE)) %>%
  ungroup()
```

```{r}
# region dummy variables
cexall <- cexall %>%
  mutate(
    regd1 = as.numeric(region == 1),
    regd2 = as.numeric(region == 2),
    regd3 = as.numeric(region == 3),
    regd4 = as.numeric(region == 4)
  )
```

```{r}
# Generate interaction terms for lwhi and lwwi with year dummies
for (i in unique(cexall$year)) {
  cexall <- cexall %>%
    mutate(
      !!paste0("lwhiy", i) := lwhi * !!sym(paste0("yrd", i)),
      !!paste0("lwwiy", i) := lwwi * !!sym(paste0("yrd", i))
    )
}
```


```{r}
# List all variables explicitly
iv_formula <- as.formula(
  "lq ~ lx + lxed2 + lxed3 + lxkid0 + lxkid1 + lxkid2 + lxkid4 + 
   age + age2 + lp + lpalc + lpfut + lptra + edd2 + edd3 + 
   regd1 + regd2 + regd3 + regd4 + cohd1 + cohd2 + cohd3 + cohd4 + 
   cohd5 + cohd6 + cohd7 + kidd0 + kidd1 + kidd2 + kidd4 + ncomp + white | 
   lwhiy1980 + lwhiy1981 + lwhiy1982 + lwhiy1983 + lwhiy1984 + lwhiy1985 + lwhiy1986 + 
   lwhiy1987 + lwhiy1988 + lwhiy1989 + lwhiy1990 + lwhiy1991 + lwhiy1992 + 
   lwwiy1980 + lwwiy1981 + lwwiy1982 + lwwiy1983 + lwwiy1984 + lwwiy1985 + lwwiy1986 + 
   lwwiy1987 + lwwiy1988 + lwwiy1989 + lwwiy1990 + lwwiy1991 + lwwiy1992"
)
```
To account for that there's more regressors than instruments, let's check:
```{r}
summary(iv_result, diagnostics = TRUE)
```

```{r}
iv_result <- ivreg(iv_formula, data = cexall, subset = (complete == 1))
```

```{r}
length(attr(terms(iv_formula), "term.labels"))  # Count regressors
length(attr(terms(iv_formula, rhs = 2), "term.labels"))  # Count instruments
```


```{r}
# Extract coefficients and save them
coef_names <- names(coef(iv_result))
coef_values <- coef(iv_result)

for (name in coef_names) {
  cexall <- cexall %>%
    mutate(!!paste0("b0_", name) := coef_values[name])
}
```

```{r}
# Save results
write.csv(cexall, "imputed_data.csv", row.names = FALSE)
```

Load in the PSID data:
```{r}
psid <- read_dta("~/Desktop/metrics_and_ml/ecma31330_final/113270/data.dta")
```

```{r}
# Merge PSID with tax data
tax_data <- read_dta("~/Desktop/metrics_and_ml/ecma31330_final/113270/tax9192.dta")
psid <- merge(psid, tax_data, by = c("id", "year"), all.x = TRUE) %>%
  mutate(ftax = ifelse(year > 1990, fiitax, ftax)) %>%
  select(-fiitax)
```

```{r}
# Regression for tax imputation
psid <- psid %>%
  mutate(y2 = y^2, y3 = y^3, y4 = y^4, y5 = y^5, fsize2 = fsize^2, post86 = year > 1986)

lm_tax <- lm(ftax ~ y + y2 + y3 + y4 + y5 + fsize + fsize2 + post86 + kids + self + asset, data = psid %>% filter(year < 1991))
psid <- psid %>%
  mutate(ftaxp = predict(lm_tax, psid)) %>%
  mutate(ftax = ifelse(year >= 1991 & is.na(ftax), ftaxp, ftax))
```

```{r}
# Save final results
write.csv(psid, "imputed_psid.csv", row.names = FALSE)
```


