---
title: "Metrics and ML - Original Imputation Method"
author: "Sydney Gu and Isabella Lin"
date: "2025-02-02"
output:
  pdf_document: default
  html_document:
    df_print: paged
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, warning=FALSE}
library(dplyr)
library(tidyr)
library(haven)
library(glmnet)
library(data.table)
library(knitr)
```

```{r}
purl("cleaning.Rmd", output = "cleaning2.R")
source("cleaning2.R")
```
Remove observations with NAs:
```{r}
cex <- na.omit(cex)
cex <- cex[cex$fout > 0, ]
set.seed(123)
total <- nrow(cex)
train_idx <- sample(1:total, size=0.7*total)
test_idx <- setdiff(1:total, train_idx)
train <- cex[train_idx, ]
test <- cex[test_idx, ]
```

```{r}
ndur_model <- lm(log(ndur) ~ log(income) + log(food) + I(log(food)^2) + log(fout) + I(log(fout)^2) + hours + hourw + year, data = train)
summary(ndur_model)
ndur_pred_log <- predict(ndur_model4, newdata = test)
ndur_pred <- exp(ndur_pred_log)
sq_diff <- (test$ndur - ndur_pred)^2
rmse <- sqrt(mean(sq_diff))
rmse
rmse_log <- sqrt(mean((log(test$ndur)-ndur_pred_log)^2))
```
```{r}
#psid <- psid %>%
 # mutate(
  #  region = as.factor(region), 
   # race = as.factor(race)       
  #)


#psid$ndur_pred <- 2.72^predict(ndur_model4, newdata = psid)

#head(psid$ndur_pred)

```

```{r}
#features <- cex %>% select(-c(ndur, ndurplus))
#pca <- prcomp(features, center = TRUE, scale. = TRUE)
#loadings <- abs(pca$rotation)
#top <- 5
#num_pcs <- 5

#top_vars <- apply(loadings[, 1:num_pcs], 2, function(x) {
 # names(sort(x, decreasing = TRUE)[1:top])
#})

#print(top_vars)
```

```{r}
#test_pca_data <- predict(pca, newdata = psid)
```

```{r}

cex$lq <- log((cex$food) / cex$pf)
cex$lp <- log(cex$pf)


model_cex <- lm(lq ~ lx + lxed2 + lxed3 + lxkid2 + lxkid3 + lxkid4 + lxy1 + lxy2 + lxy3 + lxy4 + 
                age + age2 + lp + lpalc + lpfut + lptra + edd2 + edd3 + regd1 + regd2 + regd3 + 
                cohd1 + cohd2 + cohd3 + cohd4 + cohd5 + cohd6 + cohd7 + kidd2 + kidd3 + kidd4 +
                ncomp + white, data = cex)

# Extract the coefficients from the CEX model (for use in PSID imputation)
b0 <- coef(model_cex)  # Coefficients for the non-durable consumption model

```
```{r}


# Generate necessary variables (log-transformed values)
psid$lq <- log((psid$food) / psid$pf)
psid$lp <- log(psid$pf)

# Merge with other datasets if needed, e.g., `finprice` for price data
# merge() function can be used for merging datasets

# Generate dummy variables for region, education, cohort, etc.
psid$age2 <- psid$age^2
psid$kidcat <- as.factor(psid$kids)

```

```{r}
# Apply the imputation formula from Stata using the coefficients from CEX

# Example for `lc0` imputation using the formula from Stata
psid$lc0 <- (psid$lq - (
  b0["age"] * psid$age +
  b0["age2"] * psid$age2 +
  b0["lp"] * psid$lp +
  b0["lpalc"] * psid$lpalc +
  b0["lpfut"] * psid$lpfut +
  b0["lptra"] * psid$lptra +
  # Add other terms similarly for all variables from the regression
)) / (b0["lx"] + b0["lxed2"] * psid$edd2 + b0["lxed3"] * psid$edd3 + 
       b0["lxkid2"] * psid$kidd2 + b0["lxkid3"] * psid$kidd3 + b0["lxkid4"] * psid$kidd4 +
       # Add other interaction terms here
)


```